    <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE storeProduct[
    <!ELEMENT storeProduct (product)>

    <!ELEMENT product (name, price)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>


]>
    
    
    <product>
        <name>GIGABYTE X570 AORUS XTREME</name>
        <price>₱58,462</price>
       
    </product>

    <product>
        <name> ASUS ROG Crosshair III Dark Hero </name>
        <price> ₱28,516</price>
    </product>

    <product>
        <name> ASUS ROG Strix B550-F Gaming</name>
        <price> ₱12,947.</price>
    </product>

   <product>
        <name> GIGABYTE X570 AORUS ELITE WIFI</name>
        <price> ₱12,644</price>
    </product>
    
    <product>
        <name> GIGABYTE B550M AORUS PRO-P </name>
        <price> ₱8,640 </price>
    </product>

    <product>
        <name> MSI MAG B550 TOMAHAWK  </name>
        <price>₱11,242</price>
    </product>

    <product> 
        <name>Intel Core i9-12900K</name>
        <price> ₱38,401 </price>
    </product>

    <product>
        <name> AMD Ryzen 9 5900X</name>
        <price>₱25,721</price>
    </product>

    <product>
        <name> Intel Core i7 10th Gen</name>
        <price>₱21,040</price>
    </product>

</storeProduct>